services:
  - type: worker
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~X1BNXGfs"
      - key: DATABASE_URL
        value: "postgresql://myapp_user:FaoLb6pKd0ygTd7TNYgmyiS2zjeYwZyk@dpg-d2i8do75r7bs73f7teag-a/myapp_db_adoz"
